project:
  type: website
  output-dir: docs

website:
  title: How to Health Science in R
  navbar:
    background: primary
    search: true
    left:
      - text: "About"
        file: about.qmd
      - text: "GLM: Count Data"
        file: index.qmd
      - text: "Random Intercept Model"
        file: RandomInterceptModel.qmd
      - text: "Fishers Exact Test"
        file: Fishersexactest.qmd
      - text: "Two Sample T-test"
        file: Two_sample_t.qmd
  sidebar: 
    tools:
      - icon: twitter
        href: https://twitter.com/anabananaqtpie
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/anbrav0/R-health-blog
          - text: Report a Bug
            url:  https://github.com/anbrav0/R-health-blog/issues
        

format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

 
