project:
  type: website
  output-dir: docs

website:
  title: "How to Health Science in R"
  navbar:
    right:
      - about.qmd
      - index.qmd
      - Fishersexactest.qmd
      - RandomInterceptModel.qmd
      - Two_sample_t.qmd
      - icon: github
        href: https://github.com/anbrav0
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

